version: "3.9"
services:
  demo-httpd:
    image: httpd:alpine
    volumes:
      - ./demo:/usr/local/apache2/htdocs
      - ./dist/sdatch.js:/usr/local/apache2/htdocs/sdatch.js
      - ./node_modules/bootstrap/dist/css:/usr/local/apache2/css
      - ./node_modules/bootstrap/dist/js:/usr/local/apache2/js
    ports:
      - "8080:80/tcp"
