version: "3.9"
services:
  demo-httpd:
    image: httpd:alpine
    volumes:
      - ./demo:/usr/local/apache2/htdocs
    ports:
      - "8080:80/tcp"
  tester:
    image: cimg/node:16.6.0
    volumes:
      - ./:/src